name: Kanban Board Automation

on:
  issues:
    types:
      - opened
      - closed
      - reopened
      - labeled
  pull_request:
    types:
      - opened
      - closed

jobs:
  issue_opened:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Add issue to Product Backlog
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/lealcharro/projects/3
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}

  issue_labeled_blocked:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'Blocked'
    steps:
      - name: Move to Icebox when blocked
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/lealcharro/projects/3
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
          column-name: "Icebox"

  pr_opened:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Move linked issue to In Progress
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/lealcharro/projects/3
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          column-name: "In progress"

  issue_ready_for_testing:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'Ready for Testing'
    steps:
      - name: Move to Review/QA when ready for testing
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/lealcharro/projects/3
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
          column-name: "Review/QA"

  issue_closed:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: Move to Done when closed
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/lealcharro/projects/3
          github-token: ${{secrets.PERSONAL_ACCESS_TOKEN }}
          column-name: "Done"
