name: Kanban Board Automation

on:
  issues:
    types:
      - opened
      - closed
  pull_request:
    types:
      - opened

jobs:
  add-to-in-progress:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/lealcharro/projects/1
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
          labeled: bug, enhancement
          label-operator: OR
          column-name: "In Progress"

  add-to-done:
    if: github.event_name == 'issues' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/lealcharro/projects/1
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          column-name: "Done"
